INSERT INTO subforum VALUES(1,'Dogs','Forum with topic: Dogs')
INSERT INTO subforum VALUES(2,'Cats','Forum with topic: Cats')
INSERT INTO subforum VALUES(3,'Birds','Forum with topic: Birds')
INSERT INTO subforum VALUES(4,'Fishes','Forum with topic: Fishes')
INSERT INTO threads VALUES(1,'2018-11-02 14:51:52.69','Please help me! My dog have not eaten since yesterday morning!!',TRUE,'My dog is not eating!')
INSERT INTO threads VALUES(2,'2018-11-02 14:53:03.14','Just writing to say thanks to everybody, timothy is now eating',TRUE,'My dog is now eating!')
INSERT INTO threads VALUES(3,'2018-11-02 14:59:51.32','Hi, i am a troll',TRUE,'I am a crocodile')